### ISSUE TITLE
Not able to use external Jar/Lib Files in my project

### ISSUE THREAD

**Issue by danielweide** [nus-cs2103-AY1718S1/forum#146]
I am experiencing errors like "The command "./config/travis/run-checks.sh && travis_retry ./gradlew clean checkstyleMain checkstyleTest headless allTests coverage coveralls asciidoctor" exited with 1." when i upload it to travis . It passes the run all tests but not the gradle test. 

Suggestions were to edit the Build.Gradle file but even after the changes to dependencies and Maven i realised there is still no fix for the issue. 

This is how my gradle looks like 
https://github.com/danielweide/main/blob/v1.2-final/build.gradle

Hope someone can assist me with this. Thanks !

**Comment by damithc** [comment]
@danielweide it might help if you post the link to the corresponding PR that has the failing travis log

**Comment by tshradheya** [comment]
Hey.

Just checked your repo and I am assuming that this is your Travis log for the build that failed.
https://travis-ci.org/danielweide/main/builds/291237204?utm_source=github_status&utm_medium=notification

In line 604 of log

> ERROR:.travis.yml:28: no newline at EOF.

It probably happened due to this commit as you tried to make some change something in your .travis.yml but ended up affecting the newline at EOF
https://github.com/danielweide/main/commit/85fdbbca131e28ad8062ba0e576663006968f0e5

Solution:

Just **add a newline at EOF**. There is no problem with your build.gradle file

Hope this helps

P.S Just curious as to what was the intention behind removing those lines?

**Comment by damithc** [comment]
@danielweide is this issue still relevant? Close if not.

**Comment by damithc** [comment]
Closing because this seems to be resolved. Please reopen if still not resolved.
