### ISSUE TITLE
Unable to launch the main app

### ISSUE THREAD

**Issue by huiyiiih** [nus-cs2103-AY1718S1/forum#163]
Hello everyone, 

I keep having problems with my code. I don't think my code is wrong but whenever I try to run the mainApp, the UI will never appear. And when I check it keeps saying there's Null Pointer Exception somewhere. However when I return to the master branch, which is the original code without any changes made from me, I am still unable to run the mainApp. 

Does anyone have any idea why?

**Comment by karrui** [comment]
addressbook.xml cannot be parsed because of a new feature. Delete it and it should work.

**Comment by tshradheya** [comment]
You have added a new field to store in your address book. And you probably must have put `requireNonNull()` for it.

Now since your `data/addressbook.xml` already exists and doesn't have the xml tag for that field, it gives you a NullPointerException. 

As @karrui said, delete your existing addressbook.xml and let a new one be generated by the config. Then you will no longer get the exception.

**Comment by damithc** [comment]
@huiyiiih is this issue resolved? Close issue if it is.
