### ISSUE TITLE
[W4.3d] Split Address

### ISSUE THREAD

**Issue by szalata** [nus-cs2103-AY1718S1/forum#18]
Hello,
I have created the classes as indicated on the diagram, to store the address info in separate objects instead of one long String, but then I had to make a decision regarding the format of the input. The default format, as far as I know, goes like this: a/123, Clementi Ave 3, #12-34, 231534.
We can say where the address starts and ends, but street name can comprise of numbers, block number is a number and the postal code, depending on country, may have different formats. If we let user put in this field whatever he/she chooses, how can we say what should go where?
Following all above, I have made an extra assumption that the address has 3 times ", " that separate the input, no matter if certain part of it is applicable or not, but this changes the required input and resulted in test failure on my pull request. Could you please state what I am supposed to do about the ambiguities?
Thanks in advance for help.

**Comment by damithc** [comment]
> Following all above, I have made an extra assumption that the address has 3 times ", " that separate the input, no matter if certain part of it is applicable or not, but this changes the required input and resulted in test failure on my pull request. Could you please state what I am supposed to do about the ambiguities?
> Thanks in advance for help.

@arturs68 It's ok to make these extra assumptions. The assumptions may not be realistic, but that's ok because this is just an exercise and our focus here is not on making the product realistic.

Regarding test failure, not to worry about it. We haven't covered testing yet, and I ran the tests on your PR by mistake. After we covered testing in this week's lecture, you can figure out how to modify existing tests to fit your new assumptions.
