### ISSUE TITLE
[W4.4c] exercise [addressbook-level2: LO-Exceptions]

### ISSUE THREAD

**Issue by szalata** [nus-cs2103-AY1718S1/forum#19]
Hello,
In the exercise it is written:
The current code does not handle the situation where the user deletes the storage file while the AddressBook program is running. Use exceptions to handle that situation.

I could not find a case when this causes problems. The file is read at the very beginning of the execution and if it does not exists at that point, a new one is created. Then after every update the whole data that is held in the memory is saved to the file, no matter if it exists or not. Even if we delete the file before performing the "exit" command, it still saves the data right before closing. Why and where we would consider introducing exception caused by the deletion?
Thank you for help.

**Comment by damithc** [comment]
Good question. Looks like the program automatically recovers if the file is deleted while the app is running. Try making the file 'read only' while the app is running. That situation is not handled and causes the app to crash. You can try to handle that situation better so that the application informs the user of the problem and continues to operate.
