### ISSUE TITLE
Unable to find the button to create a repository

### ISSUE THREAD

**Issue by damithc** [nus-cs2103-AY1718S1/forum#2]
Received this query from a student. Can anybody help?

>I am not sure how should I create a repository. I do not see the create button in the image given in W2.1c.

![image](https://user-images.githubusercontent.com/1673303/29491237-2e08b47e-8587-11e7-9f22-8530dcbfaeba.png)

**Comment by bokwoon95** [comment]
<img width="785" alt="screen shot 2017-08-20 at 11 36 21 am" src="https://user-images.githubusercontent.com/23723357/29491870-db99be6c-859b-11e7-8780-2217e302de70.png">

**Comment by huiyiiih** [comment]
Hello bokwoon95,

do you know if we have to link it with any accounts?

**Comment by huiyiiih** [comment]
@bokwoon95 

do we need to link it with any account?

**Comment by damithc** [comment]
> do we need to link it with any account?

I don't think so. If at all, you can link it to your GitHub account. SourceTree might force you to create an Atlassian account too IIRC (Atlassian is the company that created SourceTree).

**Comment by huiyiiih** [comment]
@damithc I have created a Atlassian account already.

**Comment by bokwoon95** [comment]
@huiyiiih 

If you're following the instructions here (https://nus-cs2103.github.io/website/book/gitAndGithub/init/index.html), it's just practice to create a local Git repository, there's no need to upload it to your own Github account. Github is used when you need to synchronize a Git repository with multiple people, since it functions like Dropbox for Git folders.

**Comment by damithc** [comment]
Closing because this seems to be resolved. Please reopen if still not resolved.
