### ISSUE TITLE
Issue about building travis

### ISSUE THREAD

**Issue by Adoby7** [nus-cs2103-AY1718S1/forum#203]
Does anyone know why this problem happens during building travis (see the red command below). It seems that there are some problems in "before cache"
https://travis-ci.org/CS2103AUG2017-W14-B4/main/builds/299958610?utm_source=github_status&utm_medium=notification
![screenshot 2](https://user-images.githubusercontent.com/25312978/32638708-8ad76074-c5fb-11e7-8274-c444f962d652.png)

**Comment by damithc** [comment]
Post link to the relevant PR?

**Comment by Adoby7** [comment]
@damithc I think this problem exists for a long time, and is hard to retrieve which feature causes it, I am trying to find it

**Comment by Adoby7** [comment]
@damithc I think this PR causes the problem firstly https://github.com/CS2103AUG2017-W14-B4/main/pull/95

**Comment by tshradheya** [comment]
I just saw your team repo, and looks like you guys have been merging failed builds for a pretty long time( 20+ failed PR's )

You should have made your master branch protected to avoid this. Now it is quite tough to figure out if the PR change had the problem or was it because the master itself was not correctly built.

You could start off by resolving these error's
![image](https://user-images.githubusercontent.com/12574756/32639401-bad2d5da-c5fe-11e7-8097-3b5db872cb27.png)

Even if your PR has no problems, since Travis builds PR's merging them to master, you will still find the build failing.

**Comment by Adoby7** [comment]
@tshradheya good news is that every thing works well after resolving these 2 errors. Thank you very much!

**Comment by damithc** [comment]
Thanks @tshradheya for saving the day 💯
