### ISSUE TITLE
When, if ever, do we use the default package-private access level?

### ISSUE THREAD

**Issue by Xenonym** [nus-cs2103-AY1718S1/forum#28]
Question as per title. The Codacy bot suggests this is a bad practice, but why?

EDIT: turns out the Codacy bot ran because I sent a PR to the wrong repo, my bad!
Would still like to know to this question anyway!

**Comment by okkhoy** [comment]
@Xenonym see if the discussion in [this SE thread](https://softwareengineering.stackexchange.com/questions/294640/is-java-package-level-scope-useful) helps? i think the accepted answer talks about why it is useful.

**Comment by Zhiyuan-Amos** [comment]
Suppose you have a `test` folder (where the test code base resides) and inside the folder you have 2 packages: `uitests` (to test for the UI components) and `commandtests` (to test that the commands are working as intended). 

Then, inside `uitests` you may have a class to set up the UI components for testing for e.g. `UIComponentSetUpHelper`. This class should never be used by `commandtests`, as such you can make the class `UIComponentSetUpHelper` to be package-private i.e. only classes within `uitests` package can use `UIComponentSetUpHelper`.

I think the reason why Codacy prompts that it's a bad practice is that we generally try to make the visibility modifier of classes, fields, and methods to be as **narrow** as possible. As such, since Codacy realizes that you can make it package-private because that class is only accessed by other classes within the same package, Codacy gave that warning.

**Comment by Xenonym** [comment]
Thanks @Zhiyuan-Amos and @okkhoy! The examples provided were helpful :)

**Comment by Zhiyuan-Amos** [comment]
@Xenonym np, glad it helped!

On a side note, @okkhoy hi Akshay, not sure if you rmb me :P

**Comment by damithc** [comment]
> On a side note, @okkhoy hi Akshay, not sure if you rmb me :P

He remembers you alright :-p. Just the other day he was asking me to recruit you as a tutor. I told him you are working for the module already :-p

**Comment by okkhoy** [comment]
@Zhiyuan-Amos I do! You can still join as a tutor, I will ramp you up to speed in an hour ;-) Will you?

**Comment by Zhiyuan-Amos** [comment]
@okkhoy aw thanks! ^^ I'll think about it and let prof know!
