### ISSUE TITLE
Travis Test failed even though files look similar

### ISSUE THREAD

**Issue by tshradheya** [nus-cs2103-AY1718S1/forum#32]
![capture](https://user-images.githubusercontent.com/12574756/30249292-c9413d2c-966b-11e7-9f94-38b0f7e14ae5.PNG)

Even though the files look same I am not able to clear the Travis testing. What could be the reason?

**Comment by damithc** [comment]
Does the test pass locally?

**Comment by charlesgohck** [comment]
If you are using runtests.sh, the expected.txt and actual.txt will have subtle differences. open both up and widen both windows. You will see that at some places on the expected.txt if the output is too long it will move the text to the next line. Not sure if there is a workaround for this. Maybe it has to do with formatting.

**Comment by damithc** [comment]
'Looks the same, but fails comparison' is often due to the differences in line endings. Windows line ending is different from the Unix one. If the two files were created on two different platforms, the two files will be considered different when they look the same.

**Comment by tshradheya** [comment]
The problem is with the line endings.

Is there a way to resolve this?

**Comment by damithc** [comment]
> Is there a way to resolve this?

I added a comment in one of your PRs. Check if a space was removed by mistake.

**Comment by charlesgohck** [comment]
@tshradheya There are three ways I can think of:

1. Check the expected.txt and edit it so that the line endings are right

2. Check the actual.txt and eyeball the output. If it is correct, copy paste over to the expected

3. I believe there are ways to convert between DOS and Unix files. I did a quick google search and found this: [Dos2Unix](https://sourceforge.net/projects/dos2unix/) Not sure if it works but I will be searching for these tools in the future.

**Comment by zameschua** [comment]
I had a similar problem before, posting my solution in case it's the same problem

My error occurs when I edited the `expected.txt` file
Found out that the files are different because of the spaces, 

Turns out Intellij automatically removes trailing spaces.

I solved it by going to `Settings -> Editor -> General -> Turn off Strip trailing white spaces on save`
![image](https://user-images.githubusercontent.com/18271085/30250337-0baa5a32-967f-11e7-9744-fca8e1bd9d2d.png)

Let me know if this helped!

**Comment by tshradheya** [comment]
@zameschua thanks a lot. That was the problem
