### ISSUE TITLE
JUnit Test Issues

### ISSUE THREAD

**Issue by LeeYingZheng** [nus-cs2103-AY1718S1/forum#38]
Hi has anyone failed some test methods StorageFileTest and/or know how to go about solving them? I have passed all other test methods and classes except for 3 of the methods in StorageFileTest. I can't quite understand what those test methods do exactly so I can't really source out the problems. 

![image](https://user-images.githubusercontent.com/31031508/30365435-55076bd0-989a-11e7-8274-9dca4baca543.png)

1. Regarding theNoSuchFileException: I see that the path to ValidData.xml file correct. I even changed the file separator in the methods from "/" to "\\" but it still doesn't work.

2. Regarding the Assertion Error, I don't understand why there is a difference in hashcode. Even though I created a new CommandTest file, I followed closely to the other commandtest files and it passed its JUnitsTest.

Will greatly appreciate any help on this matter!

**Comment by karrui** [comment]
Did you do step 11 in the [dev guide? ](https://github.com/nus-cs2103-AY1718S1/addressbook-level2/blob/master/doc/DeveloperGuide.md#design)

Observe how some tests fail. That is because they try to access the test data from the wrong directory (the working directory is expected to be the root directory, but IntelliJ runs the test with test\ as the working directory by default). To fix this issue:
Go to Run -> Edit Configurations...
On the list at the left, ensure that All in test is selected
Under Configuration, change the Working directory to the addressbook-level2 folder
Click OK
Run the tests again to ensure they all pass now.

**Comment by LeeYingZheng** [comment]
Oh I see so that was the issue..totally neglected that step. Thanks a lot @karrui , all my tests pass now! (:

**Comment by damithc** [comment]
Closing because this seems to be resolved. Please reopen if still not resolved.
