### ISSUE TITLE
Aren't interfaces only supposed to have abstract methods?

### ISSUE THREAD

**Issue by bokwoon95** [nus-cs2103-AY1718S1/forum#40]
If you look at the interface ReadOnlyPerson.java (under src/seedu/addressbook/data/person) it implements several concrete methods, which should make it count as an abstract class instead:
<img width="699" alt="screen shot 2017-09-15 at 6 03 02 pm" src="https://user-images.githubusercontent.com/23723357/30477566-2c90e418-9a40-11e7-9d68-5ef9aa7bbcea.png">

Person is a class that implements the ReadOnlyPerson interface, and it also seems to inherit the concrete methods implemented in the interface as it makes those function calls without reimplementing the functions themselves. What then, differentiates an interface from an abstract class?

**Comment by Juxarius** [comment]
https://dzone.com/articles/interface-default-methods-java
so apparently they faded the line between abstract and interfaces in Java 8 because of how the language starts to hinder modifications

i think this is a step in the right direction, the language shouldnt obstruct the programmer but act as a guide to the programmer on how the structure should be while maintaining as the bridge between the programmer and the computer.

**Comment by damithc** [comment]
Yup, interfaces can now have method implementations, narrowing the difference between abstract classes and interfaces. At CS2103 level, you can pick either one that seems to work for your situation and switch to the other one when you hit a situation where the current one doesn't work anymore but the the other does.
