### ISSUE TITLE
How do I make changes?

### ISSUE THREAD

**Issue by huiyiiih** [nus-cs2103-AY1718S1/forum#5]
Hello everyone,

How should I make changes to the fruits.txt file? 

![screen shot 2017-08-20 at 5 27 33 pm](https://user-images.githubusercontent.com/31040589/29493654-ffd67ffa-85cc-11e7-92eb-6889985c5d4b.png)

**Comment by okkhoy** [comment]
@huiyiiih as per the instructions, have you created the `fruits.txt` file in the working directory?

Once you have done that and added it to the repository, you should be able to open the text file in any editor like sublime text or notepad++. 

For the purpose of this exercise, you can simply add some text and/or remove some text from the file.

**Comment by huiyiiih** [comment]
@okkhoy yes, I have created the fruits.txt file in the working directory. It can be any directory right?

So that means for this exercise I should edit it in any editor?

**Comment by okkhoy** [comment]
What do you mean by: 
> It can be any directory right?

As long as the file is tracked by git it is sufficient.

Yes, you need to edit the file in any text editor.

**Comment by huiyiiih** [comment]
@okkhoy okay thank you.

I have another question. 
How should I start doing this? I read the setting up but realised I have to import. Where should I get the file from?


![screen shot 2017-08-20 at 7 38 36 pm](https://user-images.githubusercontent.com/31040589/29495266-7c0c18de-85ee-11e7-9a93-2bf92a40115c.png)


<img width="922" alt="screen shot 2017-08-20 at 9 29 15 pm" src="https://user-images.githubusercontent.com/31040589/29495274-a88bdc50-85ee-11e7-822e-5339dcbdce51.png">

**Comment by Skaty** [comment]
@huiyiiih

# Generally Speaking

* It can be in any subdirectory, as long as the folder structure is inside the working directory.
* As long as the content of the files are changed, a commit can be created that incorportates the changes from the file. It does not matter where/how the changes were made. It could have been automatically generated from a script/program.

# Task-specific Information

* The objective is to learn how to make changes to a file and to persist those changes to the repository (i.e. commit). Hence, in this case, it doesn't really matter where `fruits.txt` resides in relation to the root directory of the repository. For the sake of consistency, I would advise that `fruits.txt` be located in the root directory. In the future, other tasks may depend on the results of previous tasks, so it will be easier to debug should things go wrong.
* As mentioned above, yes, you can edit `fruits.txt` using any editor you fancy. Just remember to dave your changes, so that git is able to detect that you have made changes to the file.

**Comment by okkhoy** [comment]
Please take a look at the LO: W2.2b
Follow the link to Addressbook Level 1 relevant section: https://github.com/nus-cs2103-AY1718S1/addressbook-level1#set-up-a-project-in-an-ide-lo-idesetup
The instructions are present in `Part B`.

**Comment by damithc** [comment]
Closing because this seems to be resolved. Please reopen if still not resolved.
