### ISSUE TITLE
Difference between two workflows

### ISSUE THREAD

**Issue by yunpengn** [nus-cs2103-AY1718S1/forum#53]
I'm not very used to the fork workflow.

May I ask what's difference between the two workflows below?

- Create a team organisation account, create a central repository (in our case, fork from the [module's account](https://github.com/nus-cs2103-AY1718S1)). Then, every developer forks this central repository to his own account, clones from his own account, pushes all changes to his own account, then creates PR from his own account to the team organisation account.

- Create a team organisation account, create a central repository (in our case, fork from the [module's account](https://github.com/nus-cs2103-AY1718S1)). Then, every developer directly clones from this repo, and uses a separate branch to develop new features, then creates PR from new feature branch to `master` branch.

Thxs.

**Comment by damithc** [comment]
The first is the so called _forking workflow_ while the second is the _feature branch workflow_. The difference in workflow is that the first one has an extra layer because each developer has their own fork. Forking workflow is safer because only one person needs to have write access to the team repo. That way, other members cannot accidentally mess up the code base. An alternative is to use the feature branch workflow but make the master branch 'protected' (it's a GitHub feature). That way, features branch workflow can be almost as safe as the forking workflow.

**Comment by yunpengn** [comment]
Thxs for the quick reply and detailed explanation.

So which workflow is better and which one should we adopt in Phase B project?

**Comment by damithc** [comment]
We recommend the forking workflow because it is safer. But you are allowed to use other workflows, if you want to :-)

**Comment by yunpengn** [comment]
Okay, got it. Thxs prof.
