### ISSUE TITLE
Imports error upon compilation

### ISSUE THREAD

**Issue by srishag** [nus-cs2103-AY1718S1/forum#82]
![screen shot 2017-10-12 at 1 17 34 pm](https://user-images.githubusercontent.com/25860751/31480329-cec351ca-af4f-11e7-9fe6-c4508abdb6d1.png)

**Comment by damithc** [comment]
Is this a new project setup where you are compiling for the first time?

**Comment by srishag** [comment]
yes, this is the master branch where I have only edited the DeveloperGuide

**Comment by damithc** [comment]
Looks like a project dependency was not set up properly (i.e. missing a 3rd party library). Gradle is supposed to set up dependencies during the project import. Typically, this problem happens when you deviate from the project setup instructions. Try setting up the project in Intellij again, while being extra careful to follow instructions.

**Comment by srishag** [comment]
imported project using VCS in IntelliJ instead and it works now thank you!
